//
//  countries.swift
//  Origine
//
//  Created by Yann Perfy on 31/10/2023.
//
// countries list
import Foundation
let countryList = [ "Afghanistan",
                    "Afrique du Sud",
                    "Albanie",
                    "Algérie",
                    "Allemagne",
                    "Andorre",
                    "Angola",
                    "Antigua-et-Barbuda",
                    "Arabie saoudite",
                    "Argentine",
                    "Arménie",
                    "Australie",
                    "Autriche",
                    "Azerbaïdjan",
                    "Bahamas",
                    "Bahreïn",
                    "Bangladesh",
                    "Barbade",
                    "Bélarus",
                    "Belgique",
                    "Belize",
                    "Bénin",
                    "Bhoutan",
                    "Birmanie (Myanmar)",
                    "Bolivie",
                    "Bosnie-Herzégovine",
                    "Botswana",
                    "Brésil",
                    "Brunei",
                    "Bulgarie",
                    "Burkina Faso",
                    "Burundi",
                    "Cambodge",
                    "Cameroun",
                    "Canada",
                    "Cap-Vert",
                    "Centrafrique",
                    "Chili",
                    "Chine",
                    "Chypre",
                    "Colombie",
                    "Comores",
                    "Congo (République du)",
                    "Congo (République démocratique du)",
                    "Corée du Nord",
                    "Corée du Sud",
                    "Costa Rica",
                    "Côte d'Ivoire",
                    "Croatie",
                    "Cuba",
                    "Danemark",
                    "Djibouti",
                    "Dominique",
                    "Égypte",
                    "Émirats arabes unis",
                    "Équateur",
                    "Érythrée",
                    "Espagne",
                    "Estonie",
                    "États-Unis",
                    "Éthiopie",
                    "Fidji",
                    "Finlande",
                    "France",
                    "Gabon",
                    "Gambie",
                    "Géorgie",
                    "Ghana",
                    "Grèce",
                    "Grenade",
                    "Guatemala",
                    "Guinée",
                    "Guinée-Bissau",
                    "Guyana",
                    "Haïti",
                    "Honduras",
                    "Hongrie",
                    "Îles Cook",
                    "Îles Marshall",
                    "Îles Salomon",
                    "Inde",
                    "Indonésie",
                    "Irak",
                    "Iran",
                    "Irlande",
                    "Islande",
                    "Israël",
                    "Italie",
                    "Jamaïque",
                    "Japon",
                    "Jordanie",
                    "Kazakhstan",
                    "Kenya",
                    "Kirghizistan",
                    "Kiribati",
                    "Koweït",
                    "Laos",
                    "Lesotho",
                    "Lettonie",
                    "Liban",
                    "Libéria",
                    "Libye",
                    "Liechtenstein",
                    "Lituanie",
                    "Luxembourg",
                    "Macédoine du Nord",
                    "Madagascar",
                    "Malaisie",
                    "Malawi",
                    "Maldives",
                    "Mali",
                    "Malte",
                    "Maroc",
                    "Maurice",
                    "Mauritanie",
                    "Mexique",
                    "Micronésie",
                    "Moldavie",
                    "Monaco",
                    "Mongolie",
                    "Monténégro",
                    "Mozambique",
                    "Namibie",
                    "Nauru",
                    "Népal",
                    "Nicaragua",
                    "Niger",
                    "Nigeria",
                    "Norvège",
                    "Nouvelle-Zélande",
                    "Oman",
                    "Ouganda",
                    "Ouzbékistan",
                    "Pakistan",
                    "Palaos",
                    "Panama",
                    "Papouasie-Nouvelle-Guinée",
                    "Paraguay",
                    "Pays-Bas",
                    "Pérou",
                    "Philippines",
                    "Pologne",
                    "Portugal",
                    "Qatar",
                    "République dominicaine",
                    "République tchèque",
                    "Roumanie",
                    "Royaume-Uni",
                    "Russie",
                    "Rwanda",
                    "Saint-Kitts-et-Nevis",
                    "Saint-Marin",
                    "Saint-Vincent-et-les Grenadines",
                    "Sainte-Lucie",
                    "Salvador",
                    "Samoa",
                    "Sao Tomé-et-Principe",
                    "Sénégal",
                    "Serbie",
                    "Seychelles",
                    "Sierra Leone",
                    "Singapour",
                    "Slovaquie",
                    "Slovénie",
                    "Somalie",
                    "Soudan",
                    "Soudan du Sud",
                    "Sri Lanka",
                    "Suède",
                    "Suisse",
                    "Suriname",
                    "Swaziland (Eswatini)",
                    "Syrie",
                    "Tadjikistan",
                    "Tanzanie",
                    "Tchad",
                    "Thaïlande",
                    "Timor oriental",
                    "Togo",
                    "Tonga",
                    "Trinité-et-Tobago",
                    "Tunisie",
                    "Turkménistan",
                    "Turquie",
                    "Tuvalu",
                    "Ukraine",
                    "Uruguay",
                    "Vanuatu",
                    "Vatican",
                    "Venezuela",
                    "Viêt Nam",
                    "Yémen",
                    "Zambie",
                    "Zimbabwe"
]
